version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.uvicorn
      target: tester

  web:
    build:
      context: .
      dockerfile: Dockerfile.uvicorn
    ports:
      - 6780:6780
