services:
  uvicorn-test:
    build:
      context: .
      dockerfile: Dockerfile.uvicorn
      target: tester

  uvicorn-web:
    build:
      context: .
      dockerfile: Dockerfile.uvicorn
    ports:
      - 6780:6780

  granian-test:
    build:
      context: .
      dockerfile: Dockerfile.granian
      target: tester

  granian-web:
    build:
      context: .
      dockerfile: Dockerfile.granian
    ports:
      - 6781:6780
