version: "3.7"

services:
  web:
    build: .
    volumes:
      - ./api:/api
      - ./docker/logs:/logs
      - ./docker/pkgs:/pkgs
      - ./docker/envs:/envs
    ports:
      - 7000:8000
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - PYTHONPATH=/app
      - CONDA_PKGS_DIRS=/pkgs
      - CONDA_ENVS_PATH=/envs
