name: fastapi_prod_env
channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi>=0.103.1
  - python>=3.11.5
  - starlette>=0.22.0
  - uvicorn>=0.23.2
  - requests>=2.31.0
  - httpx>=0.23.1
  - gunicorn>=21.2.0
